# Generated by Django 5.0.3 on 2024-04-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_task_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_list',
        ),
    ]
