# Generated by Django 5.0.3 on 2024-04-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_task_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='house',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_list',
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
