# Generated by Django 5.0.3 on 2024-04-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_attachments_tasklist_task_task_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='completed_on',
            new_name='completed_at',
        ),
    ]
